version: 2

build:
  image: latest

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

formats: []

name: JazzHands

channels:
    - astropy

dependencies:
    - astropy
    - scipy
    - matplotlib
    - numpy
    - specutils
    - astroquery
    - pip:
        - sphinx-automodapi
        - numpydoc